spring:
  application:
    name: eureka-feign
    
server:
  port: 9001
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/    #注册中心地址
      
feign:
  hystrix:
    enabled: true
        