server:
  port: 9000
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    
ribbon:
  eager-load:
    enabled: true  
     
spring:
  application:
    name: eureka-ribbon